/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "FleChAzo",
  "description": "61",
  "base": "/-FleChAzo6/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "FleChAzo",
        "tagline": "FleChAzo6",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲 染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-2dbff42c",
      "path": "/",
      "lastUpdated": "12/15/2021, 4:35:21 PM"
    },
    {
      "title": "这是关于",
      "frontmatter": {},
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-eb39d05e",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "这是关于",
          "slug": "这是关于"
        },
        {
          "level": 3,
          "title": "一级标题",
          "slug": "一级标题"
        },
        {
          "level": 3,
          "title": "一级标题",
          "slug": "一级标题-2"
        },
        {
          "level": 3,
          "title": "一级标题",
          "slug": "一级标题-3"
        }
      ],
      "lastUpdated": "12/15/2021, 4:35:21 PM"
    }
  ],
  "themeConfig": {
    "lastUpdated": "Last Updated Time",
    "logo": "/assets/img/hero.png",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/about/"
      },
      {
        "text": "Repositories||Blog",
        "ariaLabel": "Repositories Menu",
        "items": [
          {
            "text": "github",
            "link": "https://github.com/suxuan0071"
          },
          {
            "text": "gitee",
            "link": "https://gitee.com/zc0071"
          },
          {
            "text": "csdn",
            "link": "https://blog.csdn.net/qq_42546585?spm=1000.2115.3001.5343"
          }
        ]
      }
    ]
  }
}